
import fs from 'fs';
import path from 'path';
import os from 'os';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { GoogleAIFileManager, FileState } from '@google/generative-ai/server';
import { TranscriptResult } from '@/types/youtube';
import { LLM_MODELS } from '@/config/models';
import { YtDlp } from './ytdlp';

/**
 * Generate transcript using Gemini 2.5 Flash Native Audio
 * 1. Download audio
 * 2. Upload to Gemini File API
 * 3. Generate transcript
 */
export async function generateAiTranscript(videoId: string): Promise<TranscriptResult> {
    const apiKey = process.env.GOOGLE_GENERATIVE_AI_API_KEY;
    if (!apiKey) {
        throw new Error('GOOGLE_GENERATIVE_AI_API_KEY is not set');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const fileManager = new GoogleAIFileManager(apiKey);

    // Model: Gemini 2.5 Flash
    const model = genAI.getGenerativeModel({
        model: LLM_MODELS.google.flash25
    });

    const tempFilePath = path.join(os.tmpdir(), `yt-${videoId}.mp3`);

    try {
        // 1. Download Audio (force mp3 for compatibility)
        await YtDlp.getInstance().downloadAudio(videoId, tempFilePath);

        // 2. Upload to Gemini
        console.log('[AI] Uploading audio to Gemini...');
        const uploadResult = await fileManager.uploadFile(tempFilePath, {
            mimeType: 'audio/mp3',
            displayName: `YouTube Audio ${videoId}`,
        });

        const fileUri = uploadResult.file.uri;
        let file = await fileManager.getFile(uploadResult.file.name);

        // Wait for processing
        while (file.state === FileState.PROCESSING) {
            console.log('[AI] Processing audio file...');
            await new Promise((resolve) => setTimeout(resolve, 2000));
            file = await fileManager.getFile(uploadResult.file.name);
        }

        if (file.state === FileState.FAILED) {
            throw new Error('Gemini failed to process audio file');
        }

        console.log('[AI] Audio processed. Generating transcript...');

        // 3. Generate Transcript
        const result = await model.generateContent([
            {
                fileData: {
                    mimeType: file.mimeType,
                    fileUri: fileUri,
                },
            },
            {
                text: "Generate a verbatim transcript of this audio. Output ONLY the JSON with segments. Format: { segments: [{ text: string, start: number, end: number }] }",
            },
        ]);

        // Cleanup remote file immediately
        await fileManager.deleteFile(uploadResult.file.name);

        const responseText = result.response.text();

        // Parse JSON output
        // Clean markdown code blocks if present
        const jsonStr = responseText.replace(/```json/g, '').replace(/```/g, '').trim();
        const parsed = JSON.parse(jsonStr);

        // 4. Format Result
        const segments = parsed.segments?.map((seg: any) => ({
            text: seg.text.trim(),
            startSeconds: seg.start,
            durationSeconds: seg.end - seg.start,
            isAutoGenerated: true,
        })) || [];

        const fullText = segments.map((s: any) => s.text).join(' ');

        return {
            segments,
            fullText,
            wordCount: fullText.split(/\s+/).length,
            language: 'en',
            available: true,
            isAiGenerated: true,
        };

    } catch (error: any) {
        console.error('AI Transcription failed:', error);

        // Log to file for debugging
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
            fsLog.appendFileSync(logFile, `[AI-ERROR] ${new Date().toISOString()}: ${error.message}\n${error.stack}\n`);
        } catch { }

        return {
            segments: [],
            fullText: '',
            wordCount: 0,
            language: 'en',
            available: false,
            error: error instanceof Error ? error.message : 'Unknown AI error',
        };
    } finally {
        // Cleanup local temp file
        if (fs.existsSync(tempFilePath)) {
            try {
                fs.unlinkSync(tempFilePath);
            } catch { }
        }
    }
}

