// =============================================================================
// YouTube Transcript Extraction - Extract and normalize transcripts
// =============================================================================

import type { TranscriptResult, TranscriptSegment } from '@/types/youtube';
import { YtDlp } from './ytdlp';
import os from 'os';
import path from 'path';
import fs from 'fs/promises';
import { promisify } from 'util';
import { execFile } from 'child_process';

const execFileAsync = promisify(execFile);

// =============================================================================
// Transcript Fetching
// =============================================================================

/**
 * YouTube transcript API response segment
 */
interface RawTranscriptSegment {
    text: string;
    start: number;
    duration: number;
}

/**
 * Extract transcript from YouTube video
 * 
 * Uses the youtube-transcript package which:
 * - Works without API key
 * - Handles auto-generated and manual captions
 * - Supports language selection
 * 
 * @param videoId - YouTube video ID
 * @returns Transcript result with segments and full text
 */
export async function extractTranscript(videoId: string): Promise<TranscriptResult> {
    try {
        // Force load env vars to ensure GROQ_API_KEY is available in worker context
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');

            const dotenv = await import('dotenv');
            const envPath = pathLog.join(process.cwd(), '.env.local');
            const envResult = dotenv.config({ path: envPath });

            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: CWD=${process.cwd()}\n`);
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: Env Path=${envPath}\n`);
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: Dotenv Error=${JSON.stringify(envResult.error)}\n`);
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: GROQ_API_KEY present=${!!process.env.GROQ_API_KEY}\n`);
            // Don't log the full key for security, just length
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: GROQ_API_KEY length=${process.env.GROQ_API_KEY?.length}\n`);

        } catch (e: any) {
            console.error('[Transcript] Debug logging failed:', e);
        }

        // Dynamic import to handle missing package gracefully
        const { YoutubeTranscript } = await import('youtube-transcript');

        // Fetch transcript with language fallbacks (English -> Hindi -> default available).
        let rawTranscript: RawTranscriptSegment[] = [];
        let transcriptLanguage = 'en';
        const languageAttempts: Array<'en' | 'hi'> = ['en', 'hi'];
        let lastPrimaryError: unknown;

        for (const lang of languageAttempts) {
            try {
                const result = await YoutubeTranscript.fetchTranscript(videoId, { lang });
                if (result && result.length > 0) {
                    rawTranscript = result as RawTranscriptSegment[];
                    transcriptLanguage = lang;
                    break;
                }
            } catch (error) {
                lastPrimaryError = error;
            }
        }

        if (!rawTranscript.length) {
            try {
                const result = await YoutubeTranscript.fetchTranscript(videoId);
                if (result && result.length > 0) {
                    rawTranscript = result as RawTranscriptSegment[];
                    transcriptLanguage = 'auto';
                }
            } catch (error) {
                lastPrimaryError = error;
            }
        }

        if (!rawTranscript.length) {
            if (lastPrimaryError) {
                console.error('[Transcript] Primary extraction error:', lastPrimaryError);
            }
            console.log('[Transcript] Primary extraction returned empty, triggering fallback...');
            return await fallbackToOthers(videoId);
        }

        // Convert to our format
        const segments = rawTranscript.map((segment: RawTranscriptSegment) => ({
            text: cleanTranscriptText(segment.text),
            startSeconds: segment.start,
            durationSeconds: segment.duration,
            isAutoGenerated: true, // Package doesn't distinguish
        }));

        // Normalize: merge very short segments
        const normalizedSegments = normalizeSegments(segments);

        // Build full text
        const fullText = normalizedSegments
            .map(s => s.text)
            .join(' ')
            .trim();

        return {
            segments: normalizedSegments,
            fullText,
            wordCount: countWords(fullText),
            language: transcriptLanguage,
            available: true,
        };
    } catch (error) {
        console.error('[Transcript] Primary extraction error:', error);
        // Fallback regardless of error type
        return await fallbackToOthers(videoId);
    }
}

async function fallbackToOthers(videoId: string): Promise<TranscriptResult> {
    const fallbackErrors: string[] = [];

    // Try YouTubei.js (Innertube) as fallback before AI
    try {
        const { getInnertube } = await import('./client');
        const yt = await getInnertube();
        const info = await yt.getBasicInfo(videoId);
        const transcriptData = await info.getTranscript();

        if (transcriptData?.transcript?.content?.body?.initial_segments) {
            const segments = transcriptData.transcript.content.body.initial_segments.map((segment: any) => ({
                text: cleanTranscriptText(segment.snippet.text),
                startSeconds: Number(segment.start_ms) / 1000,
                durationSeconds: Number(segment.end_ms - segment.start_ms) / 1000,
                isAutoGenerated: true,
            }));

            const normalizedSegments = normalizeSegments(segments);
            const fullText = normalizedSegments.map((s: { text: any; }) => s.text).join(' ').trim();

            return {
                segments: normalizedSegments,
                fullText,
                wordCount: countWords(fullText),
                language: 'en',
                available: true,
            };
        }
    } catch (innertubeError) {
        console.error('Innertube Transcript Fallback failed:', innertubeError);
        fallbackErrors.push(`innertube: ${String((innertubeError as any)?.message || innertubeError)}`);
    }

    // Try extracting subtitle tracks via yt-dlp (manual or auto-generated).
    try {
        const subtitleResult = await extractTranscriptFromYtDlpSubtitles(videoId);
        if (subtitleResult.available && subtitleResult.wordCount > 20) {
            return subtitleResult;
        }
        if (subtitleResult.error) {
            fallbackErrors.push(`yt-dlp subtitles: ${subtitleResult.error}`);
        }
    } catch (subtitleError) {
        console.error('yt-dlp subtitle fallback failed:', subtitleError);
        fallbackErrors.push(`yt-dlp subtitles: ${String((subtitleError as any)?.message || subtitleError)}`);
    }

    // Try local multilingual ASR fallback (faster-whisper).
    try {
        const localAsrResult = await extractTranscriptWithLocalWhisper(videoId);
        if (localAsrResult.available && localAsrResult.wordCount > 20) {
            return localAsrResult;
        }
        if (localAsrResult.error) {
            fallbackErrors.push(`local whisper: ${localAsrResult.error}`);
        }
    } catch (localAsrError) {
        console.error('Local Whisper fallback failed:', localAsrError);
        fallbackErrors.push(`local whisper: ${String((localAsrError as any)?.message || localAsrError)}`);
    }


    // Try AI Transcription if enabled
    // Only if explicitly configured with keys, otherwise skip to avoid errors
    if (process.env.GROQ_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY) {
        console.log('[Transcript] Attempting AI fallback...');
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: Triggering AI fallback for ${videoId}\n`);
        } catch { }

        try {
            const { generateAiTranscript } = await import('./ai-transcript');
            const aiResult = await generateAiTranscript(videoId);

            if (aiResult.available && aiResult.wordCount > 50) {
                try {
                    const fsLog = await import('fs');
                    const pathLog = await import('path');
                    const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
                    fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: AI success. Words: ${aiResult.wordCount}\n`);
                } catch { }
                return aiResult;
            }
        } catch (aiError: any) {
            console.error('AI Fallback failed:', aiError);
            fallbackErrors.push(`ai fallback: ${aiError.message}`);
            try {
                const fsLog = await import('fs');
                const pathLog = await import('path');
                const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
                fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: AI Fallback failed: ${aiError.message}\n`);
            } catch { }
            // Continue to return error for standard method
        }
    } else {
        fallbackErrors.push('external AI keys missing');
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: External AI keys missing, skipping AI fallback\n`);
        } catch { }
    }

    const detail = fallbackErrors.filter(Boolean).join(' | ');
    return createEmptyResult(
        detail
            ? `Failed to extract transcript after all attempts: ${detail}`
            : 'Failed to extract transcript after all attempts'
    );
}

async function extractTranscriptFromYtDlpSubtitles(videoId: string): Promise<TranscriptResult> {
    const tempDir = path.join(os.tmpdir(), `yt-subs-${videoId}-${Date.now()}`);
    try {
        const subtitlePath = await YtDlp.getInstance().downloadSubtitles(videoId, tempDir);
        if (!subtitlePath) {
            return createEmptyResult('No subtitle tracks available from yt-dlp');
        }

        const vttRaw = await fs.readFile(subtitlePath, 'utf-8');
        const segments = parseVttToSegments(vttRaw);
        const normalizedSegments = normalizeSegments(segments);
        const fullText = normalizedSegments.map((s) => s.text).join(' ').trim();
        const words = countWords(fullText);

        if (!fullText || words < 5) {
            return createEmptyResult('Subtitle track was empty after parsing');
        }

        return {
            segments: normalizedSegments,
            fullText,
            wordCount: words,
            language: 'en',
            available: true,
            isAiGenerated: false,
        };
    } finally {
        await fs.rm(tempDir, { recursive: true, force: true }).catch(() => { });
    }
}

function parseVttToSegments(vtt: string): TranscriptSegment[] {
    const lines = vtt.replace(/\r/g, '').split('\n');
    const segments: TranscriptSegment[] = [];
    let i = 0;

    while (i < lines.length) {
        const line = (lines[i] || '').trim();
        if (!line || line === 'WEBVTT' || line.startsWith('NOTE')) {
            i++;
            continue;
        }

        // Optional cue index line (numeric).
        if (/^\d+$/.test(line)) {
            i++;
        }

        const timingLine = (lines[i] || '').trim();
        const match = timingLine.match(
            /^(\d{2}:)?\d{2}:\d{2}\.\d{3}\s+-->\s+(\d{2}:)?\d{2}:\d{2}\.\d{3}/
        );
        if (!match) {
            i++;
            continue;
        }

        const [startRawRaw, endRawRaw] = timingLine.split('-->').map((s) => s.trim().split(' ')[0] || '');
        const startRaw = startRawRaw || '';
        const endRaw = endRawRaw || '';
        i++;

        const textLines: string[] = [];
        while (i < lines.length && (lines[i] || '').trim() !== '') {
            textLines.push((lines[i] || '').trim());
            i++;
        }

        const text = cleanTranscriptText(
            textLines
                .join(' ')
                .replace(/<[^>]+>/g, ' ') // remove VTT formatting tags
                .replace(/\s+/g, ' ')
                .trim()
        );

        if (text) {
            const startSeconds = vttTimeToSeconds(startRaw);
            const endSeconds = vttTimeToSeconds(endRaw);
            segments.push({
                text,
                startSeconds,
                durationSeconds: Math.max(0, endSeconds - startSeconds),
                isAutoGenerated: true,
            });
        }

        i++;
    }

    return segments;
}

async function extractTranscriptWithLocalWhisper(videoId: string): Promise<TranscriptResult> {
    const tempDir = path.join(os.tmpdir(), `yt-audio-${videoId}-${Date.now()}`);
    const audioPath = path.join(tempDir, `${videoId}.mp3`);

    try {
        await fs.mkdir(tempDir, { recursive: true });
        await YtDlp.getInstance().downloadAudio(videoId, audioPath);

        const pythonBin = process.env.PYTHON_BIN || 'python';
        const scriptPath = path.join(process.cwd(), 'scripts', 'transcribe_audio.py');
        const modelName = process.env.LOCAL_WHISPER_MODEL || 'tiny';
        const timeoutMs = Number(process.env.LOCAL_WHISPER_TIMEOUT_MS || 15 * 60 * 1000);

        const { stdout } = await execFileAsync(
            pythonBin,
            [scriptPath, '--input', audioPath, '--model', modelName],
            {
                timeout: timeoutMs,
                maxBuffer: 20 * 1024 * 1024,
            }
        );

        const parsed = JSON.parse(stdout || '{}') as {
            language?: string;
            segments?: Array<{ start: number; end: number; text: string }>;
        };

        const rawSegments = Array.isArray(parsed.segments) ? parsed.segments : [];
        const segments = rawSegments
            .filter((seg) => typeof seg?.text === 'string' && seg.text.trim().length > 0)
            .map((seg) => ({
                text: cleanTranscriptText(seg.text),
                startSeconds: Number(seg.start || 0),
                durationSeconds: Math.max(0, Number(seg.end || 0) - Number(seg.start || 0)),
                isAutoGenerated: true,
            }));

        const normalizedSegments = normalizeSegments(segments);
        const fullText = normalizedSegments.map((s) => s.text).join(' ').trim();
        const words = countWords(fullText);

        if (!fullText || words < 5) {
            return createEmptyResult('Local Whisper produced insufficient transcript text');
        }

        return {
            segments: normalizedSegments,
            fullText,
            wordCount: words,
            language: parsed.language || 'unknown',
            available: true,
            isAiGenerated: true,
        };
    } catch (error: any) {
        return createEmptyResult(
            `Local Whisper transcription failed: ${error?.message || 'Unknown local ASR error'}`
        );
    } finally {
        await fs.rm(tempDir, { recursive: true, force: true }).catch(() => { });
    }
}

function vttTimeToSeconds(value: string): number {
    const parts = value.split(':');
    if (parts.length === 2) {
        const mins = Number(parts[0] || 0);
        const secs = Number(parts[1] || 0);
        return mins * 60 + secs;
    }
    if (parts.length === 3) {
        const hours = Number(parts[0] || 0);
        const mins = Number(parts[1] || 0);
        const secs = Number(parts[2] || 0);
        return hours * 3600 + mins * 60 + secs;
    }
    return 0;
}

// =============================================================================
// Text Cleaning
// =============================================================================

/**
 * Clean transcript text
 * - Decode HTML entities
 * - Remove excessive whitespace
 * - Fix common OCR/auto-caption errors
 */
function cleanTranscriptText(text: string): string {
    return text
        // Decode HTML entities
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&nbsp;/g, ' ')
        // Remove newlines (YouTube captions use \n for line breaks)
        .replace(/\n/g, ' ')
        // Collapse whitespace
        .replace(/\s+/g, ' ')
        // Trim
        .trim();
}

/**
 * Normalize segments by merging very short ones
 * Segments < 2 words are merged with the next segment
 */
function normalizeSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
    const normalized: TranscriptSegment[] = [];
    let pendingText = '';
    let pendingStart = 0;
    let pendingDuration = 0;

    for (const segment of segments) {
        const wordCount = countWords(segment.text);

        if (wordCount < 2 && pendingText === '') {
            // Start accumulating
            pendingText = segment.text;
            pendingStart = segment.startSeconds;
            pendingDuration = segment.durationSeconds;
        } else if (pendingText !== '') {
            // Merge with pending
            pendingText += ' ' + segment.text;
            pendingDuration += segment.durationSeconds;

            // Check if we have enough now
            if (countWords(pendingText) >= 5) {
                normalized.push({
                    text: pendingText.trim(),
                    startSeconds: pendingStart,
                    durationSeconds: pendingDuration,
                });
                pendingText = '';
                pendingDuration = 0;
            }
        } else {
            // Normal segment
            normalized.push(segment);
        }
    }

    // Don't forget remaining pending
    if (pendingText !== '') {
        normalized.push({
            text: pendingText.trim(),
            startSeconds: pendingStart,
            durationSeconds: pendingDuration,
        });
    }

    return normalized;
}

// =============================================================================
// Helpers
// =============================================================================

function createEmptyResult(error: string): TranscriptResult {
    return {
        segments: [],
        fullText: '',
        wordCount: 0,
        language: 'en',
        available: false,
        error,
    };
}

function countWords(text: string): number {
    return text.trim().split(/\s+/).filter(w => w.length > 0).length;
}

/**
 * Get estimated video duration from transcript
 * (Last segment start + duration)
 */
export function getDurationFromTranscript(transcript: TranscriptResult): number {
    if (transcript.segments.length === 0) {
        return 0;
    }

    const lastSegment = transcript.segments[transcript.segments.length - 1];
    if (!lastSegment) return 0;
    return Math.ceil(lastSegment.startSeconds + lastSegment.durationSeconds);
}

/**
 * Convert transcript to timestamped text format
 */
export function transcriptToTimestampedText(transcript: TranscriptResult): string {
    return transcript.segments
        .map(segment => {
            const minutes = Math.floor(segment.startSeconds / 60);
            const seconds = Math.floor(segment.startSeconds % 60);
            const timestamp = `${minutes}:${seconds.toString().padStart(2, '0')}`;
            return `[${timestamp}] ${segment.text}`;
        })
        .join('\n');
}
