// =============================================================================
// YouTube Transcript Extraction - Extract and normalize transcripts
// =============================================================================

import type { TranscriptResult, TranscriptSegment } from '@/types/youtube';

// =============================================================================
// Transcript Fetching
// =============================================================================

/**
 * YouTube transcript API response segment
 */
interface RawTranscriptSegment {
    text: string;
    start: number;
    duration: number;
}

/**
 * Extract transcript from YouTube video
 * 
 * Uses the youtube-transcript package which:
 * - Works without API key
 * - Handles auto-generated and manual captions
 * - Supports language selection
 * 
 * @param videoId - YouTube video ID
 * @returns Transcript result with segments and full text
 */
export async function extractTranscript(videoId: string): Promise<TranscriptResult> {
    try {
        // Force load env vars to ensure GROQ_API_KEY is available in worker context
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');

            const dotenv = await import('dotenv');
            const envPath = pathLog.join(process.cwd(), '.env.local');
            const envResult = dotenv.config({ path: envPath });

            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: CWD=${process.cwd()}\n`);
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: Env Path=${envPath}\n`);
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: Dotenv Error=${JSON.stringify(envResult.error)}\n`);
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: GROQ_API_KEY present=${!!process.env.GROQ_API_KEY}\n`);
            // Don't log the full key for security, just length
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: GROQ_API_KEY length=${process.env.GROQ_API_KEY?.length}\n`);

        } catch (e: any) {
            console.error('[Transcript] Debug logging failed:', e);
        }

        // Dynamic import to handle missing package gracefully
        const { YoutubeTranscript } = await import('youtube-transcript');

        // Fetch transcript (prefers English, falls back to auto-generated)
        const rawTranscript = await YoutubeTranscript.fetchTranscript(videoId, {
            lang: 'en',
        });

        if (!rawTranscript || rawTranscript.length === 0) {
            console.log('[Transcript] Primary extraction returned empty, triggering fallback...');
            return await fallbackToOthers(videoId);
        }

        // Convert to our format
        const segments = rawTranscript.map((segment: RawTranscriptSegment) => ({
            text: cleanTranscriptText(segment.text),
            startSeconds: segment.start,
            durationSeconds: segment.duration,
            isAutoGenerated: true, // Package doesn't distinguish
        }));

        // Normalize: merge very short segments
        const normalizedSegments = normalizeSegments(segments);

        // Build full text
        const fullText = normalizedSegments
            .map(s => s.text)
            .join(' ')
            .trim();

        return {
            segments: normalizedSegments,
            fullText,
            wordCount: countWords(fullText),
            language: 'en',
            available: true,
        };
    } catch (error) {
        console.error('[Transcript] Primary extraction error:', error);
        // Fallback regardless of error type
        return await fallbackToOthers(videoId);
    }
}

async function fallbackToOthers(videoId: string): Promise<TranscriptResult> {
    // Try YouTubei.js (Innertube) as fallback before AI
    try {
        const { getInnertube } = await import('./client');
        const yt = await getInnertube();
        const info = await yt.getBasicInfo(videoId);
        const transcriptData = await info.getTranscript();

        if (transcriptData?.transcript?.content?.body?.initial_segments) {
            const segments = transcriptData.transcript.content.body.initial_segments.map((segment: any) => ({
                text: cleanTranscriptText(segment.snippet.text),
                startSeconds: Number(segment.start_ms) / 1000,
                durationSeconds: Number(segment.end_ms - segment.start_ms) / 1000,
                isAutoGenerated: true,
            }));

            const normalizedSegments = normalizeSegments(segments);
            const fullText = normalizedSegments.map((s: { text: any; }) => s.text).join(' ').trim();

            return {
                segments: normalizedSegments,
                fullText,
                wordCount: countWords(fullText),
                language: 'en',
                available: true,
            };
        }
    } catch (innertubeError) {
        console.error('Innertube Transcript Fallback failed:', innertubeError);
    }


    // Try AI Transcription if enabled
    // Only if explicitly configured with keys, otherwise skip to avoid errors
    if (process.env.GROQ_API_KEY || (process.env.GOOGLE_GENERATIVE_AI_API_KEY && process.env.AI_PROVIDER !== 'ollama')) {
        console.log('[Transcript] Attempting AI fallback...');
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: Triggering AI fallback for ${videoId}\n`);
        } catch { }

        try {
            const { generateAiTranscript } = await import('./ai-transcript');
            // Check if we are forced to use Ollama, if so, we can't really use generateAiTranscript which relies on Gemini/Groq
            if (process.env.AI_PROVIDER === 'ollama') {
                throw new Error('AI Provider is Ollama, skipping external AI transcription fallback.');
            }

            const aiResult = await generateAiTranscript(videoId);

            if (aiResult.available && aiResult.wordCount > 50) {
                try {
                    const fsLog = await import('fs');
                    const pathLog = await import('path');
                    const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
                    fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: AI success. Words: ${aiResult.wordCount}\n`);
                } catch { }
                return aiResult;
            }
        } catch (aiError: any) {
            console.error('AI Fallback failed:', aiError);
            try {
                const fsLog = await import('fs');
                const pathLog = await import('path');
                const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
                fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: AI Fallback failed: ${aiError.message}\n`);
            } catch { }
            // Continue to return error for standard method
        }
    } else {
        try {
            const fsLog = await import('fs');
            const pathLog = await import('path');
            const logFile = pathLog.join(process.cwd(), 'youtube-debug.log');
            fsLog.appendFileSync(logFile, `[Transcript] ${new Date().toISOString()}: External keys missing or Ollama enabled, skipping AI fallback\n`);
        } catch { }
    }

    return createEmptyResult('Failed to extract transcript after all attempts');
}

// =============================================================================
// Text Cleaning
// =============================================================================

/**
 * Clean transcript text
 * - Decode HTML entities
 * - Remove excessive whitespace
 * - Fix common OCR/auto-caption errors
 */
function cleanTranscriptText(text: string): string {
    return text
        // Decode HTML entities
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/&nbsp;/g, ' ')
        // Remove newlines (YouTube captions use \n for line breaks)
        .replace(/\n/g, ' ')
        // Collapse whitespace
        .replace(/\s+/g, ' ')
        // Trim
        .trim();
}

/**
 * Normalize segments by merging very short ones
 * Segments < 2 words are merged with the next segment
 */
function normalizeSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
    const normalized: TranscriptSegment[] = [];
    let pendingText = '';
    let pendingStart = 0;
    let pendingDuration = 0;

    for (const segment of segments) {
        const wordCount = countWords(segment.text);

        if (wordCount < 2 && pendingText === '') {
            // Start accumulating
            pendingText = segment.text;
            pendingStart = segment.startSeconds;
            pendingDuration = segment.durationSeconds;
        } else if (pendingText !== '') {
            // Merge with pending
            pendingText += ' ' + segment.text;
            pendingDuration += segment.durationSeconds;

            // Check if we have enough now
            if (countWords(pendingText) >= 5) {
                normalized.push({
                    text: pendingText.trim(),
                    startSeconds: pendingStart,
                    durationSeconds: pendingDuration,
                });
                pendingText = '';
                pendingDuration = 0;
            }
        } else {
            // Normal segment
            normalized.push(segment);
        }
    }

    // Don't forget remaining pending
    if (pendingText !== '') {
        normalized.push({
            text: pendingText.trim(),
            startSeconds: pendingStart,
            durationSeconds: pendingDuration,
        });
    }

    return normalized;
}

// =============================================================================
// Helpers
// =============================================================================

function createEmptyResult(error: string): TranscriptResult {
    return {
        segments: [],
        fullText: '',
        wordCount: 0,
        language: 'en',
        available: false,
        error,
    };
}

function countWords(text: string): number {
    return text.trim().split(/\s+/).filter(w => w.length > 0).length;
}

/**
 * Get estimated video duration from transcript
 * (Last segment start + duration)
 */
export function getDurationFromTranscript(transcript: TranscriptResult): number {
    if (transcript.segments.length === 0) {
        return 0;
    }

    const lastSegment = transcript.segments[transcript.segments.length - 1];
    if (!lastSegment) return 0;
    return Math.ceil(lastSegment.startSeconds + lastSegment.durationSeconds);
}

/**
 * Convert transcript to timestamped text format
 */
export function transcriptToTimestampedText(transcript: TranscriptResult): string {
    return transcript.segments
        .map(segment => {
            const minutes = Math.floor(segment.startSeconds / 60);
            const seconds = Math.floor(segment.startSeconds % 60);
            const timestamp = `${minutes}:${seconds.toString().padStart(2, '0')}`;
            return `[${timestamp}] ${segment.text}`;
        })
        .join('\n');
}
