// =============================================================================
// YouTube Types - Types for YouTube video processing
// =============================================================================

// =============================================================================
// Demo Mode Limits
// =============================================================================

/**
 * YouTube processing limits for demo mode
 * These prevent excessive resource usage
 */
export const YOUTUBE_LIMITS = {
    /** Maximum video duration in seconds (15 minutes) */
    MAX_DURATION_SECONDS: 15 * 60,

    /** Maximum number of frames to extract */
    MAX_FRAMES: 20,

    /** Frame OCR timeout in milliseconds */
    FRAME_OCR_TIMEOUT_MS: 30000,

    /** Total processing timeout in milliseconds (3 minutes) */
    TOTAL_PROCESSING_TIMEOUT_MS: 3 * 60 * 1000,

    /** Minimum frame interval in seconds */
    MIN_FRAME_INTERVAL_SECONDS: 30,

    /** Maximum frame dimension for OCR */
    MAX_FRAME_DIMENSION: 1280,
} as const;

// =============================================================================
// Video Metadata
// =============================================================================

/**
 * Metadata extracted from YouTube video
 */
export interface YouTubeVideoMetadata {
    /** Video ID (11 characters) */
    videoId: string;

    /** Video title */
    title: string;

    /** Channel name */
    channel: string;

    /** Duration in seconds */
    durationSeconds: number;

    /** Thumbnail URL */
    thumbnailUrl: string;

    /** Whether video is available (not private/deleted) */
    isAvailable: boolean;

    /** Whether transcript is available */
    hasTranscript: boolean;

    /** Canonical URL (safe, not user-provided) */
    canonicalUrl: string;
}

// =============================================================================
// Transcript
// =============================================================================

/**
 * Single transcript segment with timing
 */
export interface TranscriptSegment {
    /** Segment text */
    text: string;

    /** Start time in seconds */
    startSeconds: number;

    /** Duration in seconds */
    durationSeconds: number;

    /** Whether this is auto-generated (vs manual) */
    isAutoGenerated?: boolean;
}

/**
 * Full transcript extraction result
 */
export interface TranscriptResult {
    /** All transcript segments */
    segments: TranscriptSegment[];

    /** Combined plain text */
    fullText: string;

    /** Total word count */
    wordCount: number;

    /** Source language */
    language: string;

    /** Whether transcript was available */
    available: boolean;

    /** Error message if unavailable */
    error?: string;

    /** Whether transcript was generated by AI */
    isAiGenerated?: boolean;
}

// =============================================================================
// Frame Extraction
// =============================================================================

/**
 * Extracted frame with OCR result
 */
export interface ExtractedFrame {
    /** Frame timestamp in seconds */
    timestampSeconds: number;

    /** OCR-extracted text (empty if no text found) */
    ocrText: string;

    /** OCR confidence score (0-100) */
    confidence: number;

    /** Whether OCR found any text */
    hasText: boolean;
}

/**
 * Frame extraction result
 */
export interface FrameExtractionResult {
    /** All extracted frames with OCR */
    frames: ExtractedFrame[];

    /** Number of frames processed */
    frameCount: number;

    /** Whether frame extraction was enabled */
    enabled: boolean;

    /** Error message if extraction failed */
    error?: string;
}

// =============================================================================
// Merged Content
// =============================================================================

/**
 * Time-bucketed content segment
 */
export interface ContentBucket {
    /** Bucket start time in seconds */
    startSeconds: number;

    /** Bucket end time in seconds */
    endSeconds: number;

    /** Transcript text for this time range */
    transcriptText: string;

    /** Unique OCR text (not duplicated from transcript) */
    ocrText: string;

    /** Combined text (transcript + unique OCR) */
    combinedText: string;
}

/**
 * Merged content result
 */
export interface MergedContentResult {
    /** All content buckets ordered by time */
    buckets: ContentBucket[];

    /** Final merged plain text */
    fullText: string;

    /** Total word count */
    wordCount: number;

    /** Source breakdown */
    sources: {
        transcriptWords: number;
        ocrWords: number;
        duplicatesRemoved: number;
    };
}

// =============================================================================
// Processing
// =============================================================================

/**
 * YouTube processing configuration
 */
export interface YouTubeProcessingConfig {
    /** Whether to extract frames (requires FFmpeg) */
    enableFrameExtraction: boolean;

    /** Maximum video duration in seconds */
    maxDurationSeconds: number;

    /** Maximum frames to extract */
    maxFrames: number;

    /** Similarity threshold for deduplication (0-1) */
    deduplicationThreshold: number;
}

/**
 * Default processing config
 */
export const DEFAULT_YOUTUBE_CONFIG: YouTubeProcessingConfig = {
    enableFrameExtraction: process.env.ENABLE_FRAME_EXTRACTION === 'true',
    maxDurationSeconds: YOUTUBE_LIMITS.MAX_DURATION_SECONDS,
    maxFrames: YOUTUBE_LIMITS.MAX_FRAMES,
    deduplicationThreshold: 0.8,
};

/**
 * YouTube processing job data
 */
export interface YouTubeProcessingJob {
    /** Learning source ID */
    sourceId: string;

    /** User ID */
    userId: string;

    /** Conversation ID */
    conversationId: string;

    /** Video ID */
    videoId: string;

    /** Processing config */
    config: YouTubeProcessingConfig;
}

// =============================================================================
// API Types
// =============================================================================

/**
 * Submit YouTube URL request
 */
export interface SubmitYouTubeRequest {
    /** YouTube URL (will be validated and sanitized) */
    url: string;

    /** Conversation to add to */
    conversation_id: string;
}

/**
 * Submit YouTube URL response
 */
export interface SubmitYouTubeResponse {
    /** Created learning source */
    source: {
        id: string;
        title: string;
        status: string;
        videoId: string;
        duration: number;
    };

    /** Video metadata */
    metadata: YouTubeVideoMetadata;
}

/**
 * YouTube validation error
 */
export interface YouTubeValidationError {
    error: string;
    code: 'INVALID_URL' | 'VIDEO_TOO_LONG' | 'VIDEO_UNAVAILABLE' | 'DUPLICATE';
    details?: Record<string, unknown>;
}
